-- AlterEnum
ALTER TYPE "public"."Role" ADD VALUE 'TECNICO';

-- AlterTable
ALTER TABLE "public"."productos" ADD COLUMN     "cashMargin" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "costMargin" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "costTech" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "costTechMargin" DOUBLE PRECISION NOT NULL DEFAULT 0;
