export const AUTH_SECURITY = {
  cookiePath: "/",
  cookieSameSite: "lax" as const,
  sessionDurationSeconds: 60 * 60 * 24 * 7,
  sessionDurationMilliseconds: 1000 * 60 * 60 * 24 * 7,
  sessionTokenBytes: 32,
  sessionTokenEncoding: "hex" as const,
  sessionHashAlgorithm: "sha256",
  sessionHashEncoding: "hex" as const,
  productionEnvironmentPrefix: "prod",
  passwordSaltRounds: 12,
  minimumPasswordLength: 10,
  maximumPasswordLength: 72,
  minimumUsernameLength: 3,
  maximumUsernameLength: 40,
  usernamePattern: /^[a-z0-9._-]+$/,
} as const;
