import { QuoteDisplayStatusCode } from "@/types/workshopOperations.types";

export const WORKSHOP_OPERATIONS_ROUTES = {
  customersApi: "/client/customers",
  quotesApi: "/client/quotes",
} as const;

export const WORKSHOP_OPERATIONS_TABS = {
  overview: "overview",
  customers: "customers",
  quotes: "quotes",
  repairs: "repairs",
  catalog: "catalog",
} as const;

export const WORKSHOP_OPERATIONS_LIMITS = {
  maximumCustomerNameLength: 120,
  maximumPhoneLength: 40,
  maximumEmailLength: 160,
  maximumNotesLength: 500,
  maximumBrandLength: 80,
  maximumModelLength: 120,
  maximumImeiLength: 30,
  maximumColorLength: 60,
  maximumIssueLength: 500,
  maximumAlternativeDescriptionLength: 300,
  maximumSupplierLength: 160,
  minimumValidityDays: 1,
  maximumValidityDays: 90,
  maximumAlternatives: 10,
  minimumAlternatives: 1,
  maximumMoneyIntegerDigits: 10,
  maximumMoneyDecimalDigits: 2,
  moneyInputStep: 0.01,
} as const;

export const WORKSHOP_OPERATIONS_DEFAULTS = {
  currency: "ARS",
  validityDays: 7,
  referenceSupplier: "Proveedor de referencia",
  emptyText: "",
  emptyMetric: 0,
} as const;

export const WORKSHOP_OPERATIONS_FIELDS = {
  customerName: "customer-name",
  customerPhone: "customer-phone",
  customerEmail: "customer-email",
  customerNotes: "customer-notes",
  deviceBrand: "device-brand",
  deviceModel: "device-model",
  deviceImei: "device-imei",
  deviceColor: "device-color",
  deviceNotes: "device-notes",
  additionalDeviceCustomer: "additional-device-customer",
  additionalDeviceBrand: "additional-device-brand",
  additionalDeviceModel: "additional-device-model",
  additionalDeviceImei: "additional-device-imei",
  additionalDeviceColor: "additional-device-color",
  additionalDeviceNotes: "additional-device-notes",
  quoteCustomer: "quote-customer",
  quoteDevice: "quote-device",
  quoteIssue: "quote-issue",
  quoteValidity: "quote-validity",
  catalogSearch: "quote-catalog-search",
} as const;

export const WORKSHOP_OPERATIONS_TEXT = {
  overviewTab: "Resumen",
  customersTab: "Clientes",
  quotesTab: "Presupuestos",
  catalogTab: "Catálogo",
  customersMetric: "Clientes del taller",
  quotesMetric: "Presupuestos",
  pendingQuotesMetric: "Pendientes de respuesta",
  acceptedQuotesMetric: "Aceptados",
  overviewTitle: "Actividad del taller",
  overviewDescription: "Todos los valores provienen de clientes y presupuestos guardados.",
  noActivityTitle: "El taller está listo para trabajar",
  noActivityDescription: "Registrá el primer cliente y armá un presupuesto sin esperar el ingreso físico del celular.",
  customersTitle: "Clientes y celulares",
  customersDescription: "Conservá el contacto y los equipos asociados a cada persona.",
  createCustomerTitle: "Nuevo cliente",
  createCustomerDescription: "El primer celular se registra junto con el contacto.",
  customerNameLabel: "Nombre completo",
  customerPhoneLabel: "WhatsApp o teléfono",
  customerEmailLabel: "Correo (opcional)",
  customerNotesLabel: "Notas del cliente",
  deviceBrandLabel: "Marca",
  deviceModelLabel: "Modelo",
  deviceImeiLabel: "IMEI o serie (opcional)",
  deviceColorLabel: "Color (opcional)",
  deviceNotesLabel: "Notas del celular",
  createCustomerAction: "Guardar cliente",
  updateCustomerAction: "Guardar cambios",
  creatingCustomerAction: "Guardando...",
  customerCreated: "Cliente guardado correctamente",
  customerUpdated: "Cliente actualizado correctamente",
  deviceCreated: "Celular agregado correctamente",
  addDeviceTitle: "Agregar otro celular",
  addDeviceAction: "Agregar celular",
  selectCustomerLabel: "Cliente",
  customersListTitle: "Agenda del taller",
  customersListDescription: "Clientes, celulares y presupuestos asociados.",
  editCustomerTitle: "Editar cliente",
  editAction: "Editar",
  actionsColumn: "Acciones",
  emptyCustomers: "Todavía no registraste clientes.",
  quotesTitle: "Presupuestos",
  quotesDescription: "Costos internos, alternativas ofrecidas y aceptación manual.",
  quoteBuilderTitle: "Nuevo presupuesto",
  quoteEditorTitle: "Editar borrador",
  quoteBuilderDescription: "Puede crearse antes de que el celular ingrese físicamente.",
  quoteCustomerLabel: "Cliente",
  quoteDeviceLabel: "Celular",
  quoteIssueLabel: "Problema informado",
  quoteValidityLabel: "Validez",
  quoteValidityDescription: "Cantidad de días durante los que se respetan los precios enviados.",
  daysSuffix: "días",
  alternativesTitle: "Alternativas",
  alternativesDescription: "La lista sugiere; vos elegís proveedor, costo real y precio final.",
  alternativeDescriptionLabel: "Trabajo o repuesto",
  supplierLabel: "Proveedor elegido",
  selectedCostLabel: "Mi costo",
  referenceCostLabel: "Costo de referencia",
  suggestedPriceLabel: "Sugerencia",
  finalPriceLabel: "Precio al cliente",
  estimatedProfitLabel: "Ganancia estimada",
  manualAlternativeAction: "Agregar alternativa manual",
  removeAlternativeAction: "Quitar",
  saveDraftAction: "Guardar borrador",
  savingDraftAction: "Guardando...",
  saveQuoteTitle: "Guardar presupuesto",
  saveQuoteDescription: "Los cambios quedan como borrador hasta que marques la revisión como enviada.",
  draftCreated: "Presupuesto guardado",
  draftUpdated: "Borrador actualizado",
  cancelEditAction: "Cancelar edición",
  catalogTitle: "Buscar en la lista disponible",
  catalogSearchLabel: "Modelo o repuesto",
  catalogSearchAction: "Buscar",
  catalogSearchingAction: "Buscando...",
  addCatalogAlternativeAction: "Agregar",
  alreadyAddedAction: "Agregada",
  referenceCatalogBadge: "Lista global",
  manualBadge: "Manual",
  quotesListTitle: "Seguimiento de presupuestos",
  quotesListDescription: "Cada revisión enviada conserva exactamente los importes ofrecidos.",
  emptyQuotes: "Todavía no guardaste presupuestos.",
  quoteNumberPrefix: "Presupuesto #",
  revisionPrefix: "Revisión",
  sendRevisionAction: "Marcar como enviado",
  sendingRevisionAction: "Enviando...",
  revisionSent: "Revisión enviada y bloqueada",
  prepareRevisionAction: "Preparar nueva revisión",
  preparingRevisionAction: "Preparando...",
  editDraftAction: "Editar borrador",
  copyWhatsappAction: "Copiar mensaje",
  whatsappCopied: "Mensaje copiado para WhatsApp",
  acceptAlternativeAction: "Marcar aceptada",
  acceptingAlternativeAction: "Aceptando...",
  alternativeAccepted: "Alternativa aceptada manualmente",
  acceptedBadge: "Aceptada",
  validUntilPrefix: "Válido hasta",
  sentAtPrefix: "Enviado",
  noRevision: "El presupuesto todavía no fue enviado.",
  latestActivityTitle: "Presupuestos recientes",
  latestActivityDescription: "Estado real de los últimos presupuestos guardados en el taller.",
  workshopReadyBadge: "Operación real",
  customerRequired: "Seleccioná un cliente",
  deviceRequired: "Seleccioná un celular del cliente",
  issueRequired: "Describí el problema informado",
  alternativesRequired: "Agregá al menos una alternativa",
  customerNameRequired: "Ingresá el nombre del cliente",
  customerPhoneRequired: "Ingresá un teléfono de contacto",
  deviceBrandRequired: "Ingresá la marca del celular",
  deviceModelRequired: "Ingresá el modelo del celular",
  alternativeDescriptionRequired: "Describí la alternativa",
  supplierRequired: "Indicá el proveedor considerado",
  moneyInvalid: "Ingresá un importe válido con hasta dos decimales",
  finalPriceInvalid: "El precio al cliente debe ser mayor a cero",
  customerNotFound: "El cliente no existe",
  deviceNotFound: "El celular no existe para ese cliente",
  quoteNotFound: "El presupuesto no existe",
  quoteNotEditable: "Solo se puede editar un presupuesto en borrador",
  quoteNotSendable: "Solo se puede enviar un presupuesto en borrador",
  quoteNotReopenable: "Este presupuesto no puede abrir una nueva revisión",
  quoteNotAcceptable: "La revisión no está vigente o no puede aceptarse",
  catalogItemUnavailable: "Uno de los repuestos ya no está disponible en la lista publicada",
  imeiAlreadyExists: "Ese IMEI ya está registrado en el taller",
  whatsappGreeting: "Hola",
  whatsappIntro: "te paso el presupuesto para",
  whatsappValidity: "Los precios tienen vigencia hasta",
  whatsappClosing: "Decime qué alternativa preferís y la marco como aceptada.",
} as const;

export const QUOTE_STATUS_LABELS: Record<QuoteDisplayStatusCode, string> = {
  DRAFT: "Borrador",
  SENT: "Enviado",
  ACCEPTED: "Aceptado",
  REJECTED: "Rechazado",
  CANCELLED: "Cancelado",
  EXPIRED: "Vencido",
};
